sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
bash: wget: command not found
sudo: python: command not found

sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
2023-02-17 09:51:57 URL:https://download.calibre-ebook.com/linux-installer.py [32026/32026] -> "-" [1]
You are missing the system library libEGL.so.1. Try installing packages such as libegl1 and libopengl0

sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
2023-02-17 10:10:27 URL:https://download.calibre-ebook.com/linux-installer.py [32026/32026] -> "-" [1]
Installing to /opt/calibre
Downloading tarball signature securely...
Will download and install calibre-6.13.0-x86_64.txz
Downloading calibre-6.13.0-x86_64.txz

sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
2023-02-20 06:28:33 URL:https://download.calibre-ebook.com/linux-installer.py [32026/32026] -> "-" [1]
Installing to /opt/calibre
Downloading tarball signature securely...
Using previously downloaded calibre-6.13.0-x86_64.txz
Extracting files to /opt/calibre ...
Extracting application files...
Creating symlinks...
        Symlinking /opt/calibre/ebook-device to /usr/bin/ebook-device
        Symlinking /opt/calibre/ebook-meta to /usr/bin/ebook-meta
        Symlinking /opt/calibre/ebook-convert to /usr/bin/ebook-convert
        Symlinking /opt/calibre/ebook-polish to /usr/bin/ebook-polish
        Symlinking /opt/calibre/markdown-calibre to /usr/bin/markdown-calibre
        Symlinking /opt/calibre/web2disk to /usr/bin/web2disk
        Symlinking /opt/calibre/calibre-server to /usr/bin/calibre-server
        Symlinking /opt/calibre/lrf2lrs to /usr/bin/lrf2lrs
        Symlinking /opt/calibre/lrs2lrf to /usr/bin/lrs2lrf
        Symlinking /opt/calibre/calibre-debug to /usr/bin/calibre-debug
        Symlinking /opt/calibre/calibredb to /usr/bin/calibredb
        Symlinking /opt/calibre/calibre-parallel to /usr/bin/calibre-parallel
        Symlinking /opt/calibre/calibre-customize to /usr/bin/calibre-customize
        Symlinking /opt/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
        Symlinking /opt/calibre/calibre-smtp to /usr/bin/calibre-smtp
        Symlinking /opt/calibre/calibre to /usr/bin/calibre
        Symlinking /opt/calibre/lrfviewer to /usr/bin/lrfviewer
        Symlinking /opt/calibre/ebook-viewer to /usr/bin/ebook-viewer
        Symlinking /opt/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/
Failed to import PyQt module: PyQt6.QtCore with error: libQt6Core.so.6: cannot open shared object file: No such file or directory

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "calibre/linux.py", line 837, in setup_completion
          File "calibre/linux.py", line 582, in write_completion
          File "bypy-importer.py", line 279, in exec_module
          File "calibre/ebooks/metadata/sources/cli.py", line 15, in <module>
          File "bypy-importer.py", line 279, in exec_module
          File "calibre/utils/img.py", line 13, in <module>
        ImportError: cannot import name 'QBuffer' from 'qt.core' (/opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

Setting up desktop integration...
Failed to import PyQt module: PyQt6.QtGui with error: libQt6Core.so.6: cannot open shared object file: No such file or directory

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "calibre/linux.py", line 858, in setup_desktop_integration
          File "calibre/linux.py", line 880, in do_setup_desktop_integration
          File "calibre/linux.py", line 911, in install_xdg_junk
          File "calibre/linux.py", line 896, in install_icons
          File "calibre/linux.py", line 886, in install_single_icon
          File "calibre/linux.py", line 1308, in render_img
        ImportError: cannot import name 'QImage' from 'qt.core' (/opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

Creating un-installer: /usr/bin/calibre-uninstall


There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:

Run "calibre" to start calibre


./qt-unified-linux-x64-4.2.0-online.run
./qt-unified-linux-x64-4.2.0-online.run: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
apt-get install libfontconfig

./qt-unified-linux-x64-4.2.0-online.run
./qt-unified-linux-x64-4.2.0-online.run: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory